### ISSUE TITLE
What about a custom website provider

### ISSUE THREAD

**Issue by RainbowShatter** [polymorphicshade/Tubular#10]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

it should have the option to put spotify and other custom services on tubular

### Why do you want this feature?

Because it can get very cool and also pretty important to access content from bitView, spotify and other without an account the same way it has soundcloud and framatube

**Comment by klenndal** [comment]
Isn't this an issue for upstream NewPipeExtractor?

When trying to find an existing issue to link to, I found [this](https://github.com/TeamNewPipe/NewPipeExtractor/issues/614#issuecomment-1256591636) on NewPipeExtractor saying this feature request belongs in the main repo, and [this](https://github.com/TeamNewPipe/NewPipe/issues/6100#issuecomment-821867389) saying it belongs in the extractor.

Whatever the case, there are other apps that can act as a Spotify client for you, which will never be completely FOSS because Spotify uses Widevine DRM to encrypt the songs. Personally I think Newpipe and other downstream projects should focus on YouTube.

**Comment by polymorphicshade** [comment]
I will not be doing this, but I welcome any pull requests that add new website providers.
