### ISSUE TITLE
WHERE IS NEW VERSION OF TUBULAR??

### ISSUE THREAD

**Issue by polymorphicshade** [polymorphicshade/Tubular#109]
stop being lazy and fix the issue

**Comment by hujan86** [comment]
Upstream just released 27.1 only about 4 hours ago. If you can't wait, use NewPipe or PipePipe.

**Comment by polymorphicshade** [comment]
@hujan86 
![GE10zNjXAAAizUN](https://github.com/user-attachments/assets/f89f9e6c-6f74-4776-9472-ea08d3f842e2)

**Comment by APT37** [comment]
Damn lazy dev, can't even pull from upstream. Wonder how many days it'll take this time. Unbelievable.

**Comment by hujan86** [comment]
What's going on here? When I take a second look, OP is the owner of the Tubular repo. Is polymorphicshade not part of the dev team? At quick glance, I thought this was just some rant by a random user.

**Comment by lameventanas** [comment]
> > What's going on here? When I take a second look, OP is the owner of the Tubular repo. Is polymorphicshade not part of the dev team? At quick glance, I thought this was just some rant by a random user.
> 
> Actually there's a [quick fix](https://youtu.be/dQw4w9WgXcQ) you can apply while the dev is obviously sleeping for days on end.

Can't open the video with my broken Tubular

**Comment by hujan86** [comment]
![41h9ce](https://github.com/user-attachments/assets/3076ea8f-595f-495f-9a8b-b1e1117681e2)

**Comment by HairyMilkshakes** [comment]
i thought these were always automated whenever the "parent" updates. is that not the case? i see complaints like this on all the other variants of NewPipe too. it's a good way for me to wean off the crap for a few days anyways so no harm done :)

**Comment by towfikomar** [comment]
https://git.baalajimaestro.me/baalajimaestro/NewPipe/releases

**Comment by HairyMilkshakes** [comment]
> https://git.baalajimaestro.me/baalajimaestro/NewPipe/releases

Do you know whether this support import/export of subscription data?

**Comment by towfikomar** [comment]
> > https://git.baalajimaestro.me/baalajimaestro/NewPipe/releases
> 
> Do you know whether this support import/export of subscription data from NewPipe X? If not I guess I will find out soon.

This has a bug i found. 
Can't seek fastforward by double tap, issues an error.
So not recommend.

**Comment by HairyMilkshakes** [comment]
> > > https://git.baalajimaestro.me/baalajimaestro/NewPipe/releases
> > 
> > 
> > Do you know whether this support import/export of subscription data from NewPipe X? If not I guess I will find out soon.
> 
> This has a bug i found. Can't seek fastforward by double tap, issues an error. So not recommend.

I just tried it and it's working fine...

**Comment by sudoshindo** [comment]
> i thought these were always automated whenever the "parent" updates. is that not the case? i see complaints like this on all the other variants of NewPipe too. it's a good way for me to wean off the crap for a few days anyways so no harm done :)

I tried to look for a similar issue and I didn't find one. It seems like Poly posted this manually.

**Comment by lameventanas** [comment]
> > Can't open the video with my broken Tubular
> 
> Sorry @lameventanas, I assumed you were using NewPipe as a backup. Here's a [screenshot](https://i.ibb.co/zZ5SPDs/quick-fix.png) of the settings for you.

Thanks, but I'm using a Firefox fork that has a bug when opening animated images, and the maintainer there can't be bothered to keep his fork up to date with upstream either.

**Comment by g180** [comment]
I guess poly is showing a fix on Tubular is going to happen pretty soon and preemptively tried to kill unnecessary noise by the post.

Don't know much about how to use GitHub, but upstream NewPipe code page isn't showing the latest commit history that must have happened to release their v0.27.1, so maybe poly's waiting for a disclosure...

**Comment by kaoneko** [comment]
![Screenshot_20240712-114129_Tubular~2.png](https://github.com/user-attachments/assets/673afe6f-dda2-4371-875a-042dd401dd54)

In times like these, this button is your friend. A friend in need is a friend indeed!

No ads with Kiwi Browser + uBlock Origin. SponsorBlock probably works as well, haven't tried it.

**Comment by LoonixCube** [comment]
what a clownshow. @polymorphicshade might aswell archive this project too.

**Comment by thatguy4194** [comment]
@LoonixCube If you really, honestly are so unbelievably upset that the maintainer of this project hasn't pulled from upstream and fixed that you would not only reply to a joke post from the maintainer with a relatively ambiguous meaning, but go on to make a whole new issue for the exact same thing as the issue you just replied to where you presume the intent of the original post from the dev as being a joke issue and just assume he has given up on an extremely easy programming task, then it's probably for the better that you take a short break from youtube because you pretty clearly have some kind of problem. Poly isn't a moron and he's not a bad person either. He does this for free and if he meant to give up on this he would archive the repo, which he has done with previous projects. Maybe instead of sitting and complaining you could fork and do it yourself? You say in your own issue that all the work is done upstream anyways. If  you really care that much and if its really that easy, then do it. You might have even noticed if you bothered to read some other issues that someone has already completed an unofficial version with the new changes to use while the dev here works on his version. You literally put in more effort complaining than you would have if you just used your eyes to read you clown.

**Comment by canadiannomad** [comment]
> > Damn lazy dev, can't even pull from upstream in time. Wonder how many days it'll take him. Unbelievable.
> 
> you should ask for a refund

You know, I think I should! @polymorphicshade where should I send the money?

**Comment by LoonixCube** [comment]
> @LoonixCube If you really, honestly are so unbelievably upset that the maintainer of this project hasn't pulled from upstream and fixed that you would not only reply to a joke post from the maintainer with a relatively ambiguous meaning, but go on to make a whole new issue for the exact same thing as the issue you just replied to where you presume the intent of the original post from the dev as being a joke issue and just assume he has given up on an extremely easy programming task, then it's probably for the better that you take a short break from youtube because you pretty clearly have some kind of problem. Poly isn't a moron and he's not a bad person either. He does this for free and if he meant to give up on this he would archive the repo, which he has done with previous projects. Maybe instead of sitting and complaining you could fork and do it yourself? You say in your own issue that all the work is done upstream anyways. If you really care that much and if its really that easy, then do it. You might have even noticed if you bothered to read some other issues that someone has already completed an unofficial version with the new changes to use while the dev here works on his version. You literally put in more effort complaining than you would have if you just used your eyes to read you clown.

simp

**Comment by LoonixCube** [comment]
@thatguy4194 @LoonixCube If you really, honestly are so unbelievably upset that the maintainer of this project hasn't pulled from upstream and fixed that you would not only reply to a joke post from the maintainer with a relatively ambiguous meaning, but go on to make a whole new issue for the exact same thing as the issue you just replied to where you presume the intent of the original post from the dev as being a joke issue and just assume he has given up on an extremely easy programming task, then it's probably for the better that you take a short break from youtube because you pretty clearly have some kind of problem. Poly isn't a moron and he's not a bad person either. He does this for free and if he meant to give up on this he would archive the repo, which he has done with previous projects. Maybe instead of sitting and complaining you could fork and do it yourself? You say in your own issue that all the work is done upstream anyways. If you really care that much and if its really that easy, then do it. You might have even noticed if you bothered to read some other issues that someone has already completed an unofficial version with the new changes to use while the dev here works on his version. You literally put in more effort complaining than you would have if you just used your eyes to read you clown.

what a fat paragraph that Im not going to read from an enabler. 
UPDATE TUBULAR! its been almost a week of it taking up space on my phone.

**Comment by thatguy4194** [comment]
@LoonixCube Since you seem to have a problem with long paragraphs I will shorten my previous message down for you. 

You are a loser, and you aren't owed a thing by anyone here. People, (Including PMS) have things to do, and you can't just give people literally 2 days to pull changes from upstream like its a QTE in a video game and then say they should archive the project if they don't do it in time. He's probably just waiting until the weekend to work on his project he does for free.

That's the most important part so I condensed it for you. As a side note, I couldn't help but notice that your github history is completely empty. In fact, you've never written an issue except the one you made yesterday. I know that part because you got the badge for "first issue" on your account yesterday (I actually agree with this badge, its the first time  you became an issue on this site) . I find it interesting that you seem so confident that it should be easy to update tubular considering that it doesn't appear you've written a line of code in your life. The changes made in tubular may conflict with existing changes in newpipe, and therefore writing this update and dealing with merge conflicts actually may be challenging. Either way, you clearly have no idea.

**Comment by LoonixCube** [comment]
> @LoonixCube Since you seem to have a problem with long paragraphs I will shorten my previous message down for you.
> 
> You are a loser, and you aren't owed a thing by anyone here. People, (Including PMS) have things to do, and you can't just give people literally 2 days to pull changes from upstream like its a QTE in a video game and then say they should archive the project if they don't do it in time. He's probably just waiting until the weekend to work on his project he does for free.
> 
> That's the most important part so I condensed it for you. As a side note, I couldn't help but notice that your github history is completely empty. In fact, you've never written an issue except the one you made yesterday. I know that part because you got the badge for "first issue" on your account yesterday (I actually agree with this badge, its the first time you became an issue on this site) . I find it interesting that you seem so confident that it should be easy to update tubular considering that it doesn't appear you've written a line of code in your life. The changes made in tubular may conflict with existing changes in newpipe, and therefore writing this update and dealing with merge conflicts actually may be challenging. Either way, you clearly have no idea.

*ahem*
That's still a paragraph

**Comment by thatguy4194** [comment]
I apologize. Please consult the following diagram to get a better understanding of my intentions:
![diagram](https://github.com/user-attachments/assets/68e48d16-79e5-48fa-b878-98c4a3ed3040)

**Comment by LoonixCube** [comment]
> I apologize. Please consult the following diagram to get a better understanding of my intentions: ![diagram](https://private-user-images.githubusercontent.com/100381711/348473981-68e48d16-79e5-48fa-b878-98c4a3ed3040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzkwMjAsIm5iZiI6MTcyMDg3ODcyMCwicGF0aCI6Ii8xMDAzODE3MTEvMzQ4NDczOTgxLTY4ZTQ4ZDE2LTc5ZTUtNDhmYS1iODc4LTk4YzRhM2VkMzA0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMzUyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTdmYmFmZmZlNjhhYTI1YzBmMTA1MzJmYjY3Y2IxYmU2NTJlYjhjODllN2ZkOGFhNzE4N2JiMWFjOGExNjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lhm5h0z8pWOt9N-RKYIqPK11OyQhfVjc7TdGcwrQJHQ)

![348112399-f89f9e6c-6f74-4776-9472-ea08d3f842e2](https://github.com/user-attachments/assets/dd2c3856-b1d6-494a-9d6c-3a542e7cc64c)

**Comment by github3845** [comment]
ngl I would have preferred an ETA

**Comment by LoonixCube** [comment]
> ngl I would have preferred an ETA

how dare you

**Comment by HFPasfho** [comment]
@polymorphicshade It was kinda funny but 2 days ago. I know and appreciate that you're doing this for free, but when you have people relying on your work, even if it's voluntary, you need to maintain some semblance of professionalism. All these toxic messages from entitled people in this and other threads were started by this lack of professionalism and a cryptic joke that was understandable to people involved in the project, but not to concerned users who wanted to report a problem with the application (which the application itself asked them to do). The lack of signs of life after this news will further intensify negative emotions because it gives the feeling that nothing is being done about it. Before it was very civilized here, but this "joke" turned the entire issue tracker into a dumpster fire.
Unfortunately, the original developers are very stubborn about adding SponsorBlock support and people become frustrated in their search for a fork of a fork that doesn't get abandoned after a month or two. Although I do not share their rudeness, I understand their reasons, which also resonate with me.

**Comment by HFPasfho** [comment]
Dear @APT37 who only took 2 minutes to give me a thumbs down. What part of what I said do you dislike so much? Do you like stoking negative emotions and degrading the level of discussion in the issue tracker?

**Comment by HFPasfho** [comment]
> > @polymorphicshade It was kinda funny but 2 days ago. I know and appreciate that you're doing this for free, but when you have people relying on your work, even if it's voluntary, you need to maintain some semblance of professionalism. All these toxic messages from entitled people in this and other threads were started by this lack of professionalism and a cryptic joke that was understandable to people involved in the project, but not to concerned users who wanted to report a problem with the application (which the application itself asked them to do). The lack of signs of life after this news will further intensify negative emotions because it gives the feeling that nothing is being done about it. Before it was very civilized here, but this "joke" turned the entire issue tracker into a dumpster fire. Unfortunately, the original developers are very stubborn about adding SponsorBlock support and people become frustrated in their search for a fork of a fork that doesn't get abandoned after a month or two. Although I do not share their rudeness, I understand their reasons, which also resonate with me.
> 
> If you only need SponsorBlock, use PipePipe. The latest APK is available in the [official releases](https://github.com/InfinityLoop1308/PipePipe/releases) and [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/InfinityLoop1309.NewPipeEnhanced).

If using PipePipe was enough for me, I wouldn't waste my time and dev time writing on Tubular issue tracker, I hope this is clear.

**Comment by polymorphicshade** [comment]
holy shit what happened here?

I wait a few days until I have an ounce of free time on the weekend, and everyone is pissing themselves

**Comment by KraXen72** [comment]
consoomers can't cope without youtube, gotta yap in github issues. take ur time poly. others are welcome to use pipepipe or grayjay or anything else in the meantime :)

**Comment by sudoshindo** [comment]
> holy shit what happened here?
> 
> I wait a few days until I have an ounce of free time on the weekend, and everyone is pissing themselves

welcome to the modern internet where everyone's attention span is so brainrotted they need to always be watching a video, have it at 2x speed, have the ability to autoskip all sponsors, and if one of these things can't be done their brain starts to implode so they start banging on the door of the poor unsuspecting open source dev that makes the thing they use.

**Comment by chefexperte** [comment]
Hey, @ everybody who helped fix the app this time, a big thank you from me! 
I've seen all the issues created and the people going crazy and thought hey maybe someone should say thank you. 
@polymorphicshade if you have some donation link I'd be happy to say thank you that way as well (idk if it was only poly, in the commit history it looks like it?)

**Comment by polymorphicshade** [comment]
> Hey, @ everybody who helped fix the app this time, a big thank you from me! 
> I've seen all the issues created and the people going crazy and thought hey maybe someone should say thank you. 
> @polymorphicshade if you have some donation link I'd be happy to say thank you that way as well (idk if it was only poly, in the commit history it looks like it?)

Donate to the NewPipe devs here: https://newpipe.net/donate/

I don't want your money.

**Comment by lp35** [comment]
> holy shit what happened here?
> 
> I wait a few days until I have an ounce of free time on the weekend, and everyone is pissing themselves

Can't understand our world any more. I found people very agressive on this repo since the Youtube issue. It's like you are offering food for free in the street, and people get angry about it and throw it in your face because it does not taste like they want. Those are the questions you might self-ask if there is angriness inside you:

1. Real addition to tubular is to NOT see ads when watching videos. How much it really costs to watch ads for a few days, waiting for an update? Only time? Doing the math tell me that people are spending much more time complaining on this repo, than watching 5sec of ads for those few days instead.

2. Need to download a video? There are plenty of website where you can download by copy pasting link. And as said in other posts, they are a lot of alternative in the meantime.

3. People that talk about the lack of professionalism: 

  1. What do you tell to your boss if he/she calls you to work on the weekend, or when you're back home after your day of work and ask to go back to code?
  2. Do ones lives are depending on this project, so the maintainer deserve to be pissed of because people are dying? **We are talking here about an app for entertainment**!
  3. Do you know how to code and how much time it is needed to provide stable code? **Don't shit in the hand that is giving you food**

No one deserve to be attacked **by any way** when they provide their free time. None of those agressive people here would have behave like they did if they had the developer in front of them.

Open-source maintainer burn-outs are madly high those days, pushing maintainers in this direction will likely end with a closed-source world in few years, and it would be YOUR responsability. World would be much better if people got less self-centered, there is enough violence off the internet nowadays !!!

Thank you for your **work** @polymorphicshade !

**Comment by HairyMilkshakes** [comment]
> holy shit what happened here?
> 
> I wait a few days until I have an ounce of free time on the weekend, and everyone is pissing themselves

you VILL do it for free and you VILL like it when i demand you do it

**Comment by thatguy4194** [comment]
@polymorphicshade Thank you for your work! I apologize for derailing the issue a bit.

**Comment by g180** [comment]
Now I see a release. Thank NewPipe devs, @UndeRus, @polymorphicshade and all who contribute each project.

**Comment by sudoshindo** [comment]
> Donate to the NewPipe devs here: https://newpipe.net/donate/
> 
> I don't want your money.

UNFATHOMABLY BASED

**Comment by KraXen72** [comment]
hello, just letting you guys know that the fix for the error around the one minute mark was pushed to the newpipeextractor earlier today.
