### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by LoonixCube** [polymorphicshade/Tubular#113]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/Tubular/releases/latest).
- [X] I am *not* able to reproduce the bug with the *latest version* of [vanilla NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/Tubular/issues) or [closed](https://github.com/polymorphicshade/Tubular/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the vanilla NewPipe [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Opened Tubular on Monday the 8th to download some podcasts for the work week (its broken)
2. Opened Tubular on Tuesday (broken)
3. Opened Tubular on Wednesday (broken)
4. Opened Tubular on Thursday (still broken)
5. Did not bother opening Tubular today (Friday) (still broken)

### Expected behavior

I expect the dev (polymorphicshade) to refrain from smugly hand-waving their responsibility as the maintainer of this project (which is mostly all upstream btw) and to show hundreds of users why they should keep this fork installed.

### Actual behavior

dog reaction pics and self-mockery was encountered.

### Affected Android/Custom ROM version

GrapheneOS (Android Linux)

### Affected device model

Pixel 6a

**Comment by TDavLinguist** [comment]
I'm not sure whether this is a giant meme or written seriously, but I'll respond as if this is written seriously, since a bunch of 14-year olds keep asking where the updated release is.

FOSS Developers don't owe the users anything. Tubular is a passion project and if polymorphicshade doesn't have the time to release it, then s/he doesn't have the time. That's it. We, as users of a FOSS project have a few options, fortunately.
1. Move to the upstream project (TeamNewPipe/NewPipe)
2. Move to another downstream project (i.e. PipePipe)
3. Merge the necessary changes and create a pull request for polymorphicshade to review
4. Wait

Badgering a dev is a surefire way to get the dev to burn out and abandon a project completely. Tubular is *not* the same as NewPipeSponsorBlock as there are several UI and Extractor changes that require manual changes (reply comments were neglected for a long time on upstream NewPipe, but were re-implemented in Tubular). The dev has to make sure that implementing the changes doesn't break anything else in the project. So be patient and let PMS work. PMS is aware of the upstream update as PMS him/herself created the satirical issue #109 to poke fun at the lack of an update.

As other commenters have said in #109 and #111, if you need to watch YouTube videos quickly, do one of the four things I mentioned above.

If this issue is indeed a troll, then well played. You had me fooled.

**Comment by LoonixCube** [comment]
@TDavLinguist 
> I'm not sure whether this is a giant meme or written seriously, but I'll respond as if this is written seriously, since a bunch of 14-year olds keep asking where the updated release is.
> 
> FOSS Developers don't owe the users anything. Tubular is a passion project and if polymorphicshade doesn't have the time to release it, then s/he doesn't have the time. That's it. We, as users of a FOSS project have a few options, fortunately.
> 
>     1. Move to the upstream project (TeamNewPipe/NewPipe)
> 
>     2. Move to another downstream project (i.e. PipePipe)
> 
>     3. Merge the necessary changes and create a pull request for polymorphicshade to review
> 
>     4. Wait
> 
> 
> Badgering a dev is a surefire way to get the dev to burn out and abandon a project completely. Tubular is _not_ the same as NewPipeSponsorBlock as there are several UI and Extractor changes that require manual changes (reply comments were neglected for a long time on upstream NewPipe, but were re-implemented in Tubular). The dev has to make sure that implementing the changes doesn't break anything else in the project. So be patient and let PMS work. PMS is aware of the upstream update as PMS him/herself created the satirical issue #109 to poke fun at the lack of an update.
> 
> As other commenters have said in #109 and #111, if you need to watch YouTube videos quickly, do one of the four things I mentioned above.
> 
> If this issue is indeed a troll, then well played. You had me fooled.

I'm waiting one more day.

**Comment by HairyMilkshakes** [comment]
Either wait it out or replace it with another one... there are plenty out there.

**Comment by artkiver** [comment]
NewPipe only tagged 0.27.1 yesterday: https://github.com/TeamNewPipe/NewPipe/tags

It takes time to downstream changes to forked projects, patience is a virtue.

Try it.

**Comment by TDavLinguist** [comment]
@LoonixCube 
> @TDavLinguist
> I'm waiting one more day.
Then please close this issue. That is the courteous thing to do. We all know PMS is working on it, and having duplicate issues is a waste of space.

**Comment by TheBSODAndWSODFan** [comment]
@LoonixCube try this build https://github.com/UndeRus/Tubular/releases/tag/0.27.0000

**Comment by TDavLinguist** [comment]
> "OMG the free software that i'm using isn't updated, because someone who don't get paid to maintained didn't do his job"
> 
> You know this is opensource, you can fork it and apply the patches yourself

I suppose OP could always offer to pay polymorphicshade for his/her time.

**Comment by Lennethinian** [comment]
”FOSS devs don't owe their users anything"
They do. If they don't want it they shouldn't make public releases and take on responsibility. All of you dickriders are forgetting how PS used to release new updates as soon as NewPipe updated.
I'd be willing to cut him some slack if he previously posted an update that would explain a possible break in pattern but he didn't as far as I know he didn't. So he could just be lazy for all we know.
"go do it yourself, then"
You go do it, if you're so inclined to be an armchair programmer and defend anytime they're late. It genuinely can't be difficult if he usually updates them so quickly.
Personally I've been waiting in silence, but if I have do put up with this chickenshit idol worship of someone who fails to show up  and upda6e people, I'll go switch to someone who at least earns their proverbial keep while being worshipped by people no encourage a lack of standards.

And no, I'm not fucking paying him. If I need to give him money just for him to do something he voluntarily decided to do, then he isn't worth wasting a penny on. Please stop with these excuses.

**Comment by LoonixCube** [comment]
I sleep
